// <auto-generated />
using System;
using Api.Auth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Api.Auth.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190817183539_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Api.Auth.Data.AuthCredentials", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .HasColumnName("Password");

                    b.Property<int>("RegistrationStateId")
                        .HasColumnName("Relation_State_Id");

                    b.HasKey("Email");

                    b.ToTable("Auth_Credentials");
                });

            modelBuilder.Entity("Api.Auth.Data.JwtRefreshToken", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Email");

                    b.Property<string>("Key")
                        .HasColumnName("Key");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnName("Valid_To");

                    b.HasKey("Email");

                    b.ToTable("Jwt_Refresh_Token");
                });
#pragma warning restore 612, 618
        }
    }
}
